bayandin/awesome-awesomeness

README.md
Collection of open-source software made in Sweden.
=> Added awesome-swedish-opensource

README.md
Repository at https://github.com/dahlia/awesome-sqlalchemy.  Way to go @dahlia!
=> Add awesome-sqlalchemy

README.md
Adds [go-patterns](https://github.com/tmrts/go-patterns) curated collection.
=> Add awesome-go-patterns

README.md
Add Amazon Web Services awesome list.
=> Add Amazon Web Services.

README.md
Added functional programming resources list to the General List
=> Add Functional Programming

README.md
https://github.com/Friz-zy/awesome-linux-containers
=> add 'Linux Containers' into 'General'

README.md
=> added awesome-selfhosted

README.md
=> Remove zeef link as it is *very* outdated

README.md
=> add Awesome Angular 2

README.md
Language homepage: http://crystal-lang.org
Source code: https://github.com/crystal-lang/crystal
Refers to #189 
/cc @m1guelpf
=> Add Crystal lang

Dangerfile
=> [WIP]Continous Integration system

README.md
**https://github.com/joubertredrat/awesome-devops**
**List about DevOps tools, fixes #220 **
=> Add Awesome DevOps

README.md
README list was duplicated in README.
=> Removed duplicate "README" list

README.md
https://github.com/aviaryan/awesome-no-login-web-apps
Curated list of awesome web apps that work without requesting you to create an account.
cc @m1guelpf #279
=> Added awesome-no-login-web-apps

README.md
=> Added a linksheet for programming newsletters

README.md
https://github.com/ChristosChristofidis/awesome-deep-learning
=> Deep Learning

README.md
A curated list of awesome code formatting tools and libraries
=> Add Code Formatting Tools and Libraries

README.md
This project is all about monitoring tools and monitoring plugins and monitoring addons.
Used for monitoring your OS, network, storage, database,  business data and so on.
=> Add General monitoring.

README.md
**https://github.com/arbox/nlp-with-ruby**
**This list encompasses Ruby related projects for processing natural language texts. It it an attempt to create a curated list with only working software and no dead links. The list is focused only on Ruby so it does not duplicate available lists.**
Please consider adding it to your awesome collection :)
=> Add NLP with Ruby.

README.md
[Awesome JavaScript learning resources ](https://github.com/micromata/awesome-javascript-learning-resources)
This list is about JavaScript – the language. Not about APIs, tooling, frameworks or other aspects of todays JavaScript ecosystem.
Therefore the list is small and focused to best resources. Reason: We don’t want to frustrate people who like to learn JavaScript with a list that:
- is too long to get through it
- offers too many possibilities
=> Add link to JavaScript learning resources

README.md
- Add Awesome MongoDB
- Add Awesome Ansible
=> Fix wrong indentation on Awesome Ansible

README.md
**N/A**
**I'm fixing the formatting of existing lists**
=> Adjust formatting for Vim

README.md
An awesome list for Kotlin: https://github.com/KotlinBy/awesome-kotlin
=> Add Kotlin

README.md
https://github.com/kdeldycke/awesome-falsehood
Fix #287
=> Add awesome falsehood

README.md
**https://github.com/pedronveloso/awesome-android-release-notes**
**Android ecysystem is vast and this list makes it easy to keep track with all the things pertinent to one's subset, specially given that all the information is scattered across different webpages**
=> Add Awesome Android Release Notes

README.md
**https://github.com/coreb1t/awesome-pentest-cheat-sheets**
**[Pentest Cheat Sheets -  Collection of cheat sheets useful for pentesting]**
=> Pentest Cheat Sheets Added

README.md
**https://github.com/brookshi/awesome-typescript-projects**
**Great open source projects written in TypeScript, include Editor, Framework, UI, Library**
=> Add TypeScript Projects

README.md
**https://github.com/meirwah/awesome-incident-response**
**This list contains several resources like tools and books about incident response (cybersecurity).**
=> Added Incident Response

README.md
**https://github.com/chiraggude/awesome-laravel**
**A curated list of awesome bookmarks, packages, tutorials, videos and other cool resources from the Laravel ecosystem.**
=> Add Laravel resources

README.md
https://github.com/vuejs/awesome-vue
Frontend lib similar to Angular, React, +49k stars.
=> + VueJS, fixed React

README.md
**https://github.com/carpedm20/awesome-hacking**
**It's a curated list of awesome Hacking tutorials, tools and resources**
=> Add curated list for Hacking

README.md
**https://github.com/Hunter-Github/awesome-space-books**
**The list contains titles of books (and sometimes, links to their legal full text versions online) instrumental in learning space technology, history, capabilities of rockets. Ancillary lists link to more specialized and less mainstream resources (papers on Alcubierre drive, for instance).**
=> Adding space-related books list

README.md
**https://github.com/owainlewis/awesome-artificial-intelligence**
**This is list of artificial intelligence topics, but somehow is missing here in awesome-awesomeness collection**
=> Add [Artificial intelligence]

README.md
The repository is under fsprojects now.
=> Update link to Awesome F#

README.md
**https://github.com/rust-unofficial/awesome-rust**
**awesome-rust has just moved**
=> awesome-rust is now at rust-unofficial

README.md
Remove NodeJS link by @vndmtrx - Not working
=> Remove NodeJS by @vndmtrx - Not working

README.md
https://github.com/flagello/awesome-sveltejs
Svelte: a front-end template library for compiling components to plain JavaScript.  Pretty awesome.
=> Add "Svelte" under "JavaScript"

README.md
<https://github.com/ellerbrock/awesome-koa>
Awesome List for Koa.js Framework
cheers maiky
=> feat(readme): add awesome koa

README.md
https://github.com/ellerbrock/awesome-typescript
Add Awesome-Typescript to this awesome list :)
Cheers Maik
=> feat(readme): add awesome-typescript

README.md
**https://github.com/guillaume-chevalier/awesome-deep-learning-resources**
**Added a new awesome Deep Learning list :)**
=> Add a Deep Learning list

README.md
**https://github.com/nmec/awesome-ember**
**A JavaScript framework for creating ambitious web applications.**
=> Add Ember.js to the JavaScript section

README.md
** https://github.com/sneg55/curatedseotools **
** I've created Curatedseotools and got featured on ProductHunt with 800+ upvotes(reaching Top 10 Most Upvoted Products at SEO Tools Category). When I started this site, I was thinking about it as a source of trusted and time proved SEO tools for Digital Marketers. **
=> Added Curatedseotools list into SEO

README.md
Added this list to the "General" category.
**[https://github.com/LappleApple/awesome-leading-and-managing]**
**[List of resources on leading people and being a manager. Geared toward tech, but potentially useful to anyone. It's worth including because it's one of the top (the top?) lists of its kind on GitHub and very active/updated almost daily.]**
=> Added Leadership and Management list

README.md
https://github.com/troxler/awesome-css-frameworks
The repository is a collection of CSS frameworks (e.g. from CSS resets to complete general purpose frameworks like Bootstrap). The collection is categorized and sorted by the number of GitHub stars. Each project has a description and links to a demo, documentation, and repository (if applicable). The goal of the collection is to provide a suitable styling for different web projects and to show the diversity of such frameworks.
=> Add CSS Frameworks

README.md
Add Matlab to general sections
**[https://github.com/mikecroucher/awesome-MATLAB](https://github.com/mikecroucher/awesome-MATLAB)**
**A curated list of awesome MATLAB toolboxes, applications, software, and resources. MATLAB is a multi-paradigm numerical computing environment.**
=> Add Matlab

README.md
**https://github.com/carlosperate/awesome-microbit**
**The micro:bit is a small programmable embedded board designed to make learning and teaching easy and fun (http://microbit.org).**
=> Add micro:bit

README.md
awesome deep-rl added
https://github.com/tigerneil/awesome-deep-rl
**[Explain what this list is about and why it should be included here.]**
=> awesome deep-rl added

README.md
**[Insert URL to the list here.]**
https://github.com/sirredbeard/Awesome-UNIX
**[Explain what this list is about and why it should be included here.]**
This list is about the history and influence of UNIX and UNIX philosophy. UNIX philosophy pervades computer science and it's approach dominates current development, on Linux, macOS, Android, and even increasingly Windows.
- [x ] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. For example, `Add [Name of List]`, not `Update readme.md` or `Add an awesome …
=> Added Awesome UNIX

README.md
**https://github.com/Twilio-org/awesome-twilio**
**Curated repository of useful and generally awesome Twilio-related tools and technologies for programmatic communication services**
=> Add `awesome-twilio` list to the master list

README.md
**https://github.com/joaomilho/awesome-idris**
**Idris is a general purpose pure functional programming language with dependent types. Dependent types allow types to be predicated on values, meaning that some aspects of a program’s behaviour can be specified precisely in the type. It is compiled, with eager evaluation. Its features are influenced by Haskell and ML.**
#320 
=> Add awesome idris

README.md
**https://github.com/coinpride/CryptoList**
**Curated collection of blockchain & cryptocurrency resources.**
=> Add CryptoList

README.md
**https://github.com/toddmotto/public-apis**
**A collective list of public JSON APIs for use in web development.**
=> Add public-apis

README.md
**[https://github.com/anaibol/awesome-serverless]**
**[Additional awesome list with the awesome solutions of serverless tools and similar]**
=> Add awesome serverless link (https://github.com/anaibol/awesome-serverless)

README.md
**https://github.com/bnb/awesome-hyper**
**Hyper plugins, themes, and resources**
=> Add awesome-hyper

README.md
**https://github.com/binhnguyennus/awesome-scalability**
> A curated list of selected readings to illustrate Scalability, Availability, and Stability Design Patterns in Back-end Development.
=> Add Awesome Scalability

README.md
**https://github.com/amir-arad/awesome-osc**
**applications, libraries and gateways for OSC protocol*
=> add OSC (open sound control)

README.md
The Awesome list can be found here: https://github.com/lawrencegripper/awesome-servicefabric
Service Fabric is a distributed systems platform for Linux and Windows that makes it easy to package, deploy, and manage scalable and reliable microservices and containers. It is the infrastructure that most of Microsoft's cloud solution Azure is built upon.
=> Service Fabric awesomeness list for Service Fabric development and operations

README.md
https://github.com/quobit/awesome-python-in-education
awesome-python-in-education lists educational resources with Python as the programming language. I included it under Python because that's how the Javascript section is structured.
=> Add Python > awesome-python-in-education

README.md
- Blockchain
- [by @imbaniac](https://github.com/imbaniac/awesome-blockchain)
- [by @coderplex](https://github.com/coderplex/awesome-blockchain)
- [by @hitripod](https://github.com/hitripod/awesome-blockchain)
- [by @iNiKe](https://github.com/iNiKe/awesome-blockchain)
- [by @igorbarinov](https://github.com/igorbarinov/awesome-blockchain)
- [by @istinspring](https://github.com/istinspring/awesome-blockchain)
- [by @openblockchains](https://github.com/openblockchains/awesome-blockchains)
- [by @kennethreitz](https://github.com/kennethreitz/awesome-coins)
- [awesome-token-sale](https://github.com/holographicio/awesome-token-sale)
- Bitcoin
- [by @btcbrdev](https://github.com/btcbrdev/awesome-btcdev)
- [by @igorbarinov](https://github.com/igorbarinov/awesome-bitcoin)
- Ethereum
- [by …
=> General > Bitcoin -> Blockchain > {Blockchain, Bitcoin, Ethereum}

README.md
**https://github.com/Jolg42/awesome-typography**
**I created this list in June 2016, the list now contains +300 resources that are useful when programming with fonts. This repository received multiple PR by third parties and more and more people are using it now!**
=> Add Awesome Typography

README.md
**[https://github.com/ZYSzys/awesome-captcha]**
**[This is a collection of awesome captcha libraries and captcha crack tools.]**
=> add Captcha

README.md
Added link to new awsome list of software design patterns
https://github.com/DovAmir/awesome-design-patterns
**https://github.com/DovAmir/awesome-design-patterns**
**This is a list of design patterns, not only GOF but also architectual patterns, cloud patterns etc..
Many people are interested in patterns to quickly get to the gist of a subject but I havn't found any other list of design patterns resources.**
- [v ] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [v ] This pull request has a descriptive title. For example, `Add [Name of List]`, not …
=> update readme with awesome-design-patterns

README.md
**https://github.com/Solido/awesome-flutter**
**Flutter is Google framework for native mobile apps with Material Design widget**
=> Add Awesome Flutter

README.md
Added link to new list of blockchain and cryptocurrency resources
**[https://github.com/0xtokens/awesome-blockchain]**
**[This list contains resources about blockchain, cryptocurrencies and everything related to digital assets like smart contracts, mining, exchanges and others.]**
=> Add Blockchain

README.md
**https://github.com/GustavBertram/awesome-common-lisp-learning-list**
**This is a curated list of Common Lisp learning resources, which is different from the previous CL list that only lists libraries.**
=> Adding Common Lisp learning list

README.md
**https://github.com/trekhleb/learn-python**
**Collection of Python scripts that are split by topics and contain code examples with explanations, different use cases and links to further readings**
=> Add link to "Playground and cheatsheet for learning Python"

README.md
https://github.com/andrewda/awesome-frc
This list contains a bunch of useful resources for teams competing in the FIRST Robotics Competition. This list includes both programming languages and software.
=> Add FIRST Robotics Competition

.github/pull_request_template.md
The repository is an exhaustive list of graph representation learning research papers with reference implementations. The machine learning task is to create representations of whole graphs from a database e.g. molecules, financial transaction graphs etc. It covers factorization models, graph kernels, statistical fingerprints and deep learning.
**[https://github.com/benedekrozemberczki/awesome-graph-embedding]**
**[The repository is an exhaustive list of graph representation learning research papers with reference implementations. The machine learning task is to create representations of whole graphs from a database e.g. molecules, financial transaction graphs etc. It covers factorization models, graph kernels, statistical fingerprints and deep learning.]**
Failure to properly do so will …
=> Add awesome graph embedding repository.

.github/pull_request_template.md
Reverts bayandin/awesome-awesomeness#355
=> Revert "Add awesome graph embedding repository."

README.md
**[https://github.com/benedekrozemberczki/awesome-graph-embedding]**
**[The repository is an exhaustive list of graph representation learning research papers with reference implementations. The machine learning task is to create representations of whole graphs from a database e.g. molecules, financial transaction graphs etc. It covers factorization models, graph kernels, statistical fingerprints and deep learning.]**
- [ x] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. For example, `Add [Name of …
=> Add awesome graph embedding list.

README.md
**https://github.com/Tom2718/Awesome-Ethereum#readme**
Ethereum is a blockchain platform for distributed computing. This particular list aims to keep up to date with the rapidly evolving space - a lot of the other resources contain broken link or information that is now wrong/deprecated. 
**Note:** Considering the other repo has not been updated within 3 years.
=> Add Ethereum

README.md
**[https://github.com/benedekrozemberczki/awesome-community-detection]**
**[The repository is a collection of papers on community detection - graph clustering. Each paper has the title, authors, a link to the paper and a reference implementation from GitHub. The methods covered include matrix factorization, tensor decomposition cyclic pattern based  clustering and deep learning among many other procedures. The papers listed are from the best machine learning, data mining, network science conferences and journals.]**
=> Add awesome community detection repository

README.md
[https://github.com/dreamingechoes/awesome-mental-health](https://github.com/dreamingechoes/awesome-mental-health)
A curated list of awesome articles, websites and resources about mental health in the software industry.
=> Add Mental Health

README.md
added component library awesome list - https://github.com/anubhavsrivastava/awesome-ui-component-library
**https://github.com/anubhavsrivastava/awesome-ui-component-library**
**This is list about UI Component Libraries based on various UI styleguides and from consumption point of UI styleguides component libraries are used in UI frameworks**
=> Add UI Component list for styleguides

README.md
Just added my cocoa-controls list
**https://github.com/v-braun/awesome-cocoa**
**List contains cocoa controls for iOS and OSX**
Remark:
The list **IS** a generated markdown file based on a json file to be flexible in the layouting.
See the [contributing section](https://github.com/v-braun/awesome-cocoa#contributing)
=> Added cocoa-controls

README.md
https://github.com/VPashkov/awesome-nim
For the Nim programming language.
=> Add Nim programming language

README.md
URL to add: https://github.com/k4m4/terminals-are-sexy
A curated list of Terminal frameworks, plugins & resources for CLI lovers
=> Add `terminals are sexy`

README.md
Added my awesome list for Apache Kafka.
**https://github.com/monksy/awesome-kafka**
**The list is a merge of other awesome-kafka lists that haven't been updated, organized, or accepting PRs for a while. This is an up-to-date list accepting PRs.**
=> Added the awesome-kafka link.

README.md
**https://github.com/alexk111/awesome-bitcoin-payment-processors**
**A list of awesome bitcoin payment processors and stories from merchants using them.**
=> Add Bitcoin Payment Processors

README.md
https://github.com/myshov/awesome-mobile-web-development
There are great articles about mobile web development, there are tools for creating great mobile experience. But there is no awesome list about this topic yet.
=> Add Mobile Web Development

README.md
https://github.com/markusschanta/awesome-jupyter
A curated list of awesome Jupyter projects, libraries and resources. The Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text.
At present, there are about [1.5 million Jupyter notebooks tracked on GitHub](https://github.com/parente/nbestimate) and the number is steadily increasing. There is a large number of projects related to Jupyter and this list can serve as an entry point to get an overview of the space.
The list that I would like to add currently has 704 stars, 120 commits, 85 items on the list and 98 forks. It's getting more and more traction.
Thanks, Markus
Failure to properly do so will just result in the pull request …
=> Add Jupyter

README.md
**https://github.com/puresec/awesome-serverless-security/**
**A curated list of serverless security resources, articles, presentations and blogs**
- [V] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [V] This pull request has a descriptive title. For example, `Add [Name of List]`, not `Update readme.md` or `Add an awesome list`.
- [V] The list I added **has been around for at least 20 days**,
- [V] The list I added is a non-generated Markdown file in a GitHub repo,
- [V] The list I added is not a duplicate
=>  Changes to be committed: Add Serverless-Security

README.md
[Prometheus](https://github.com/roaldnefs/awesome-prometheus) => Curated list of Prometheus resources.
and
[Prometheus alerting rules](https://github.com/samber/awesome-prometheus-alerts) => A curated list of Prometheus alerting rules.
=> Adding Prometheus 📊 🚨

README.md
**https://github.com/ocaml-community/awesome-ocaml**
**Original Awesome OCaml was moved into the new organization, thus fixing the link**,
see https://github.com/ocaml-community/awesome-ocaml/issues/147 for the reference.
=> Fix the Awesome OCaml link

README.md
https://github.com/bcoe/awesome-cross-platform-nodejs
Libraries and resources related to writing Node.js that works on Windows, Mac, Linux and BSD, by @bcoe.
Why this matters: according to the [2018 Node.js user survey](https://nodejs.org/en/user-survey-report/#Primary-OS-Distro), 24% of Node.js developers use Windows locally and 41% use Mac. In production 85% use Linux and 1% use BSD.
=> Add Cross-platform Node.js

README.md
https://github.com/r0f1/datascience
I created a list for resources for data science with Python. It includes not only libraries, but also links to tutorials, code snippets, blog posts and talks. The existing awesome list focues on papers, my list focuses on mainly on packages and is quite different. Think it would be a good addition to this repo.
=> Added Data Science with Python

README.md
**https://github.com/HussainAther/awesome-philosophy**
**This list is a collection of philosophical texts across various disciplines to introduce anyone to philosophy. **
=> Add philosophy

README.md
**https://github.com/HussainAther/awesome-ethics**
**A curated list of sources and reasoning to introduce readers to ethics from a philosophical angle. We discuss several branches of ethics and how they relate to one another while listing sources in philosophy to introduce readers to ethics.**
=> Add Ethics to introduce readers to ethics and remove indents

README.md
https://github.com/simskij/awesome-software-architecture
A curated list of awesome resources on software architecture. Includes resources on architectural tools, frameworks, methods, design patterns and more. 
✅  I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
✅ This pull request has a descriptive title. 
✅ The list I added has been around for at least 20 days.
✅ The list I added is a non-generated Markdown file in a GitHub repo.
✅ The list I added is not a duplicate.
=> add software architecture

README.md
**https://github.com/lorabv/awesome-agile**
**This list includes various resources about Agile methodolies, including cermonies, story pointing, metrics, and many more.**
=> Add Awesome Agile

README.md
https://github.com/nerox8664/awesome-computer-vision-models
It's the list with popular deep learning models with corresponding evaluation metrics. The models aggregated by type and sorted by article's year.
=> Add computer vision models list.

README.md
https://github.com/vinjn/awesome-vulkan
This is a curated list of tools, libraries and other resources relating to the Khronos Vulkan API.
=> Add Vulkan

README.md
https://github.com/AdrienTorris/awesome-blazor
A Curated list of resources about Blazor, a .NET web framework using C#/Razor and HTML that runs in the browser with WebAssembly.
=> Add Blazor

README.md
**[https://github.com/bipinvaylu/awesome-kotlin-native]**
**[A curated list of multiplatform libraries & resources that support full stack: Mobile(Android/iOS), Web(JavaScript), Backend and Desktop.]**
=> Add Kotlin/Native

README.md
**https://github.com/oskar-j/awesome-image-coloring**
**A curated list of awesome AI-powered image coloring frameworks, libraries, and software. I believe there is no similar repository at the moment which would exhaustively list all interesting "colorization projects" using Artificial Intelligence. Most of those project make for automatic colorization of images, yet some of them require some knowledge on machine learning and/or some skills to set them up. Have fun!**
=> Add General Image coloring

README.md
**[https://github.com/krzjoa/awesome-python-data-science](https://github.com/krzjoa/awesome-python-data-science)**
**Software for Data Analysis, Visualization and Machine Leaning in Python.**
=> Add Python Data Science

README.md
**[Insert URL to the list here.]**
https://github.com/thibmaek/awesome-raspberry-pi
**[Explain what this list is about and why it should be included here.]**
Additional awesome Raspberry Pi list.
=> Add awesome Raspberry Pi by thibmaek 

README.md
**https://github.com/aliesbelik/awesome-jmeter**
**This curated collection includes all the plugins, integration capabilities, testing techniques, learning resources, best practices and other things used for load-testing and performance measurement activities using [Apache JMeter](http://jmeter.apache.org/), popular open-source testing tool.**
=> Add JMeter

README.md
**https://github.com/TheJambo/awesome-testing**
**A curated list of software testing resources. Seems to be a good company for the [List of Free Software Testing Resources](https://github.com/ligurio/awesome-software-quality), already present in this collection.**
=> Add Testing

README.md
**https://github.com/ramnes/awesome-mongodb**
**Fixing link for Awesome MongoDB to correct repo. This will fix issues #346 and #352.**
=> Fix MongoDB

README.md
**https://github.com/HenryHoggard/awesome-arm-exploitation**
**A collection of awesome videos, articles, books, tools and resources about ARM exploitation.**
=> Add ARM Exploitation

README.md
**https://github.com/leomaurodesenv/game-datasets**
**Materials and datasets for Artificial Intelligence in games.**
=> Add Game Dataset

README.md
**https://github.com/LisaDziuba/Awesome-Design-Tools**
**Design tools used pretty much by any developer who has any design related work**
=> Add design tools

README.md
**[https://github.com/benedekrozemberczki/awesome-monte-carlo-tree-search-papers]**
**[A curated list of Monte Carlo tree search papers with implementations. ]**
=> Add Monte Carlo Tree Search Papers

README.md
**https://github.com/soroushchehresa/awesome-coronavirus**
**Useful projects and resources for COVID-19 (2019 novel Coronavirus)**
=> Add Coronavirus

README.md
Closes #334
**https://github.com/damon-kwok/awesome-package-manager**
**Awesome package manager resources.**
=> awesome-package-manager

README.md
**https://github.com/TaptuIT/awesome-devsecops**
**This list is a collection of resources and tooling related to DevSecOps. DevSecOps is an extension of DevOps - a methodology and philosophy for software development - that aims to incorporate security expertise and testing into the development lifecycle, with the goal of creating more secure software.**
**This list of resources can help software development teams learn about and adopt DevSecOps practices and tooling, resulting in more secure software for everybody.**
=> Add DevSecOps

README.md
https://github.com/componently-com/awesome-building-blocks-for-web-apps
Standalone features to be integrated into web applications. It should be included because it's awesome not having to code the same functionality over and over again.
=> Add Building Blocks for Web Apps

README.md
Official awesome repository for V Language
**https://github.com/vlang/awesome-v**
**This list contains links to resources for V Language.**
=> Add awesome list for V lang

README.md
Just a fix for previous commit. Sorry for the mistake.
=> fix(v-lang): moves awesome for VLang to next line

README.md
add web effect and langding page
[https://github.com/nordicgiant2/awesome-landing-page](https://github.com/nordicgiant2/awesome-landing-page)
A series of beautiful and practical landing page templates
=> add web effect and langding page

README.md
https://github.com/pFarb/awesome-crypto-papers
This list is a collection of cryptographic papers (white papers) for security engineers, that helps them creating secure systems. This collection is well-organized, contains "classic" cryptographic papers, like explaining how AES GCM works or how to find collisions in MD5, as well as "fresh" research, for example, post-quantum crypto.
I'm adding Awesome Crypto Papers list below Cryptography section. I believe it should be a separate entrance, because this one is focused on crypto papers, not libs/tools.
=> Add Awesome Crypto Papers

README.md
Remove broken link from the readme. The following URL returns 404
https://github.com/jaspergould/awesome-asm
=> Remove Broken Link

README.md
**[https://github.com/protontypes/awesome-robotic-tooling]**
**[This list collects free tools for professional robotic development in C++ and Python with a touch of ROS, autonomous driving and aerospace. It is now the largest of free robotic tools. I maintain it for 1 year. Every day I try to find some new packages that I can add to the list. Many tools in the list have been used by myself in professional applications. ]**
=> Add Awesome Robotic Tooling List

README.md
https://github.com/jaredthecoder/awesome-vehicle-security
A curated list of awesome resources, books, hardware, software, applications, people to follow, and more cool stuff about vehicle security, car hacking, and tinkering with the functionality of your car.
=> add vehicle security

README.md
**[https://github.com/protontypes/awesome-sustainable-technology](https://github.com/protontypes/awesome-sustainable-technology)**
**[Open source projects sustaining stable climate, energy supply and vital natural resources. So far there is no comparable list in this area. Sustainable technologies concern us all and ensure that knowledge and technology in this area will remain our superiority in the long term.]**
=> Add Sustainable Technology

README.md
**https://github.com/SaintFenix/Awesome-BSD-Ports-Programs-And-Projects**
**This repository functions as a list of interesting ports, programs, and Projects for newbies and veterans to BSD, it largest exists to fill the void of lack of resources for the BSD operating system, as very little of it seems to be available on Github as a whole.**
=> Add Awesome-BSD-PPP List

README.md
**[https://github.com/rossant/awesome-math]**
**[Because it's about math]**
=> Add link to awesome-math repo

README.md
https://github.com/mjhea0/awesome-fastapi
List of resources associated with FastAPI, a Python web framework. I feel like it's worth an add since you've included a Django list. FastAPI along with Django and Flask are the most popular Python web frameworks.
=> Add FastAPI

README.md
Added awesome list of threat intelligence under General
**[https://github.com/hslatman/awesome-threat-intelligence]**
**[This is a list of cyber threat intelligence sources, platforms, methodologies and standards]**
=> Added awesome list of threat intelligence to README.md

README.md
https://github.com/miketheman/awesome-taglines
Well, simply put, it's awesome. And it's awesome about other awesome things.
=> Add Taglines to the awesomeness

README.md
Hi,
[https://github.com/mehdihadeli/awesome-dotnet-core-education](https://github.com/mehdihadeli/awesome-dotnet-core-education)
Collection of useful articles and resources to learning and practicing about .Net Core and its related technologies.
=> Add DotNet-Core-Education List

README.md
Hi 👋
https://github.com/asyraffff/Open-Source-Ruby-and-Rails-Apps
List of awesome open source applications written in Ruby and Rails. The main goal of this repository is to find free open source Ruby and Rails apps and start contributing 🚀 .
=> add Open-Source-Ruby-and-Rails-Apps

README.md
**https://github.com/LinuxCafeFederation/awesome-android**
**This is a list of awesome open-source Android applications, it should be included because it is a very curated list and its topic certainly interests many people.**
=> Add Android Apps

README.md
**Link**: https://github.com/talentlessguy/awesome-node-esm
**Description**: This list is a collection of Node.js libraries that support ESM out of the box. Currently, majority of Node.js libraries are CommonJS only and for that reason named imports aren't supported. This list provides libraries that either have dual target or they target Node ESM at once, meaning that you can safely use named imports with them without any transpiler like Babel.
=> Add Node ESM to JavaScript > Node.js sub-category

README.md
https://github.com/aniftyco/awesome-tailwindcss
The org in which the [Awesome Tailwind CSS](https://github.com/aniftyco/awesome-tailwindcss) repo has changed a while ago, so just updating it to reflect correctly here.
=> Update Tailwind CSS repo url

README.md
**[https://github.com/nhivp/Awesome-Embedded.]**
**[Adding list of Embedded related resources]**
=> Add Embedded

README.md
**[https://github.com/ohenley/awesome-ada]**
**[Adding list of resources for Ada(Spark) programming language]**
=> Add Ada(Spark)

README.md
**[https://github.com/Hack-with-Github/Awesome-Hacking]**
**[Adding list of resources for hacking by user:Hack-with-Github]**
=> Add Hacking by user:Hack-with-Github

README.md
**https://github.com/jpomykala/awesome-i18n**
**List is getting traction so I think it's useful for many people**
=> Add Internationalization

README.md
**https://github.com/jupyter-naas/awesome-notebooks**
**Ready to use data science templates, organized by tools to jumpstart your projects in minutes. 😎 published by the Naas community.**
=> Add notebooks

README.md
**https://github.com/riderx/awesome-capacitor**
**This list provides resources on Capacitor to help anyone start building web native apps. It focuses on the plugins part for now but will be enhanced with the community.**
=> Add Capacitor listing
